### ISSUE TITLE
可否增加参数，指定txt文件位置，以及-y自动重写host的功能？

### ISSUE THREAD

**Issue by xingkoo** [Ponderfly/GoogleTranslateIpCheck#1]
如题，功能增强。以便写到定时任务中，定时检测并重写host。
包括删除txt文件进入扫描模式，同样可以通过参数，设置是否当无可用ip时自动删除txt并进入扫描械。
这么差的网络环境，让脚本自动执行，能极大减少需要人为干扰的情况。

**Comment by SongSongK** [comment]
> 如自动功能增强。以便写入到定时任务中，定时检测并删除文件主机。 删除txt模式，同样可以通过设置，是否当无可用ip时并进入扫描工具。 这样的包括网络环境，让脚本自动执行，极大地减少需要人为干扰的情况。

好建议，定时任务自动运行，减少人为干预

**Comment by Ponderfly** [comment]
可以使用参数
 -s 可以直接进入扫描模式
 -y 自动写入Host文件
目前Ip还是比较稳定的,不需要频繁设置,可以先使用计划任务自动运行

**Comment by SongSongK** [comment]
> 可以使用参数 -s 可以直接进入扫描模式 -y 自动写入Host文件 可以通过配置文件指定txt文件 位置 目前Ip还是比较稳定的,不需要频繁设置,可以先使用计划任务自动运行

感谢！
