### ISSUE TITLE
win10上运行软件，所有的ip都超时

### ISSUE THREAD

**Issue by ysjZ173173** [Ponderfly/GoogleTranslateIpCheck#10]
我在win10上用管理员身份运行GoogleTranslateIpCheck.exe，命令窗出现的所有ip都超时，删除了ip.txt后重新运行也是超时，请问我是少了什么配置吗
![image](https://user-images.githubusercontent.com/31580331/204179110-e2cca771-711a-4aa7-9811-d6b6b0d4c96e.png)

**Comment by Ponderfly** [comment]
有没有开代理软件之类的

**Comment by jingjingxyk** [comment]
可以参考这个办法: https://github.com/GoodCoder666/GoogleTranslate_IPFinder/issues/1#issuecomment-1325319373

**Comment by ysjZ173173** [comment]
> 有没有开代理软件之类的,开了需要关掉

谢谢，确实是开了代理造成的
