### ISSUE TITLE
现在这个工具已经几乎完全失效了[已经解决]

### ISSUE THREAD

**Issue by XBTree493** [Ponderfly/GoogleTranslateIpCheck#16]
几乎所有的谷歌翻译服务器IP地址已经全部无法Ping通，猜测不再是以前污染DNS来屏蔽了
手动解析也没找到可用的
不确定是否是个个例

**Comment by Ponderfly** [comment]
你个人的问题,很有肯能是开了代理

**Comment by XBTree493** [comment]
确实是我个人的问题，但是我没有开任何代理，不知道昨天电信那边出了什么幺蛾子
