### ISSUE TITLE
IP都能拼通但是定向无效

### ISSUE THREAD

**Issue by klcb2010** [Ponderfly/GoogleTranslateIpCheck#18]
![Screenshot_2023-01-11-18-24-47-943_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/32628414/211782587-3326b094-c65b-4566-aa4e-c5b8509d3738.jpg)
试了今天最新的IP地址 设定translate.googleapis.com 定向到142.251.9.90
![Screenshot_2023-01-11-18-25-21-251_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/32628414/211782374-1b624efb-3039-4d1e-8040-f2b3a564d492.jpg)

**Comment by Ponderfly** [comment]
你要直接访问翻译网页还要添加  142.251.9.90 translate.google.com

**Comment by klcb2010** [comment]
> 你要直接访问翻译网页还要添加 142.251.9.90 translate.google.com

加了 translate.google.com  直接定向到 谷歌了
![Uploading Screenshot_2023-01-12-02-38-00-132_io.github.forkmaintainers.iceraven.jpg…]()

**Comment by Ponderfly** [comment]
> > 你要直接访问翻译网页还要添加 142.251.9.90 translate.google.com
> 
> 加了 translate.google.com 直接定向到 谷歌了 ![Screenshot_2023-01-12-02-38-00-132_io github forkmaintainers iceraven]
手机不好改host 你直接用这个https://translate.amz.wang

**Comment by klcb2010** [comment]
> > > 加了 translate.google.com 直接定向到 谷歌了 !
> 
> 手机不好改host 你直接用这个https://translate.amz.wang

谢谢不常用
