### ISSUE TITLE
希望增加参数退出控制台窗口或者自动退出控制台窗口

### ISSUE THREAD

**Issue by tdk-kedion** [Ponderfly/GoogleTranslateIpCheck#19]
希望增加参数退出控制台窗口或者自动退出控制台窗口，通过批处理文件实现开机自动设置，可以更加方便快捷

**Comment by Ponderfly** [comment]
以增加在 -y 模式下自动退出

**Comment by Jaasdsa** [comment]
希望增加参数退出控制台窗口或者自动退出控制台窗口，每次计划任务后，还要点一次，期待后台完全静默运行
![image](https://user-images.githubusercontent.com/29112372/231046278-6108372d-3d77-496b-83ca-336d7dba6071.png)

**Comment by Ponderfly** [comment]
> 希望增加参数退出控制台窗口或者自动退出控制台窗口，每次计划任务后，还要点一次，期待后台完全静默运行 ![image](https://user-images.githubusercontent.com/29112372/231046278-6108372d-3d77-496b-83ca-336d7dba6071.png)

操作里面把参数加上

**Comment by tdk-kedion** [comment]
> 希望增加参与退出控制窗口或自动退出控制窗口，每次计划任务后，还要点一次，期待后台完全静默运行 ![图像](https://user-images.githubusercontent.com/29112372/231046278-6108372d-3d77-496b-83ca-336d7dba6071.png)
推荐使用批处理运行，可以自动管理员运行和退出
@echo off
%1 mshta vbscript:CreateObject("Shell.Application").ShellExecute("cmd.exe","/c %~s0 ::","","runas",1)(window.close)&& exit
GoogleTranslateIpCheck.exe -y
