### ISSUE TITLE
1.5版本上传错误windows

### ISSUE THREAD

**Issue by wyx-666** [Ponderfly/GoogleTranslateIpCheck#21]
1.5版本上传错误windows

**Comment by Ponderfly** [comment]
用1.6的试试

**Comment by wyx-666** [comment]
我用了1.6的可以

**Comment by wyx-666** [comment]
[![image](https://user-images.githubusercontent.com/62326362/215336307-37c6b12f-5159-4cbe-90fb-b542936d52f5.png)
](http://tva1.sinaimg.cn/large/007ie4mxly1hakxodrqnqj31hc0p27ca.jpg)

**Comment by wyx-666** [comment]
很奇怪看不到1.6

**Comment by wyx-666** [comment]
![image](https://user-images.githubusercontent.com/62326362/215336443-e6a6ed80-60f6-447c-ae19-16db6d54e845.png)

**Comment by wyx-666** [comment]
你看一下，我觉得或许你上传的有一点点问题

**Comment by wyx-666** [comment]
https://github.com/Ponderfly/GoogleTranslateIpCheck/releases

这个链接没有1.6

**Comment by Ponderfly** [comment]
改不了了 下个版本在调整

**Comment by wyx-666** [comment]
没事，我就是和你说一下，我觉得我不说，你不容易发现
