### ISSUE TITLE
比较好奇这个IP段是怎么得来的?

### ISSUE THREAD

**Issue by pkptzx** [Ponderfly/GoogleTranslateIpCheck#25]
比较好奇这个ip段是怎么获取到的.  
原本我以为是通过DNS查询 类似 [GitHub520](https://github.com/521xueweihan/GitHub520) 
看了代码发现是IP段扫描判断, 我就比较好奇这个ip段是怎么来的了.真厉害.  
我找了google的接口获取ip段,但范围都比你提供的大,不知道你通过什么手段精简了?.

**Comment by Ponderfly** [comment]
慢慢扫出来的,而且不能只是去ping 或者扫描证书,很多能通不能用
