### ISSUE TITLE
删除ip.txt后，长时间从服务器获取IP无反应的解决办法

### ISSUE THREAD

**Issue by hak5ya** [Ponderfly/GoogleTranslateIpCheck#39]
由于GitHub Proxy的主域名 ghproxy.com 已 GFW，所以需要更换代理加速域名。详情请见[GitHub Proxy](https://ghproxy.com/)官网。
具体操作如下
将config.json中远程IP文件URL修改为https://mirror.ghproxy.com/https://github.com/Ponderfly/GoogleTranslateIpCheck/releases/download/1.1.1/ips.txt
同理
远程IPv6文件URL修改为
https://mirror.ghproxy.com/https://github.com/Ponderfly/GoogleTranslateIpCheck/releases/download/1.1.1/IPv6.txt
保存后即可正常使用IP检测

**Comment by Ponderfly** [comment]
已经更新
