### ISSUE TITLE
你好，hosts文件已添加64.233.188.144 translate.googleapis.com 64.233.188.144 translate.google.com 64.233.188.144 translate-pa.googleapis.com，但是还是无法进行英文网页的翻译，谷歌翻译的网页也无法进入，该如何解决呢，谢谢

### ISSUE THREAD

**Issue by xinguo1236** [Ponderfly/GoogleTranslateIpCheck#45]
你好，hosts文件已添加64.233.188.144 translate.googleapis.com
64.233.188.144 translate.google.com
64.233.188.144 translate-pa.googleapis.com，但是还是无法进行英文网页的翻译，谷歌翻译的网页也无法进入，该如何解决呢，谢谢

**Comment by Ponderfly** [comment]
你能ping通不,这IP我这不通了

**Comment by xinguo1236** [comment]
您好，我执行ping 64.233.188.144
ping translate.googleapis.com
ping translate.google.com
ping translate-pa.googleapis.com
均显示请求超时，但是这个IP是今天上午我用GoogleTranslateIpCheck.exe得到的，请问我现在应该如何操作呢，重新执行一下GoogleTranslateIpCheck.exe吗，谢谢您



***@***.***
 
发件人： Ponderfly
发送时间： 2024-04-27 11:02
收件人： Ponderfly/GoogleTranslateIpCheck
抄送： xinguo1236; Author
主题： Re: [Ponderfly/GoogleTranslateIpCheck] 你好，hosts文件已添加64.233.188.144 translate.googleapis.com 64.233.188.144 translate.google.com 64.233.188.144 translate-pa.googleapis.com，但是还是无法进行英文网页的翻译，谷歌翻译的网页也无法进入，该如何解决呢，谢谢 (Issue #45)
你能ping通不,这IP我这不通了

**Comment by Ponderfly** [comment]
重新运行下吧

**Comment by xinguo1236** [comment]
您好，我多次尝试，并且在已经删除ip.txt的情况下，管理员身份执行，使用显示 如果支持IPv6推荐优先使用,使用参数 -6 启动
未能找到IP文件
尝试从服务器获取IP
获取服务器IP失败
开始扫描可用IP,时间较长,请耐心等候
扫描完成,找到 0 条IP

开始检测IP响应时间

未找到可用IP,可删除 ip.txt 文件直接进入扫描模式
然后界面一直不动，这种是正常现象吗，谢谢，麻烦您了


***@***.***
 
发件人： Ponderfly
发送时间： 2024-04-27 15:36
收件人： Ponderfly/GoogleTranslateIpCheck
抄送： xinguo1236; Author
主题： Re: [Ponderfly/GoogleTranslateIpCheck] 你好，hosts文件已添加64.233.188.144 translate.googleapis.com 64.233.188.144 translate.google.com 64.233.188.144 translate-pa.googleapis.com，但是还是无法进行英文网页的翻译，谷歌翻译的网页也无法进入，该如何解决呢，谢谢 (Issue #45)
重新运行下吧

**Comment by Ponderfly** [comment]
试试这几个
142.250.0.90
142.250.27.90
142.250.71.130
142.250.71.133
142.250.71.136
142.250.71.131
142.250.71.134
142.250.71.143
142.250.71.139
142.250.71.152
142.250.71.153
142.250.71.138
142.250.71.145
142.250.71.160
142.250.71.162
142.250.71.165
142.250.71.168
142.250.71.170
142.250.71.167
142.250.71.171
142.250.71.173
142.250.71.174
142.250.71.164
142.250.71.149
142.250.71.161
142.250.71.166
142.250.71.177
142.250.71.178
142.250.71.181
142.250.71.163
142.250.71.159
142.250.71.184
142.250.71.169
142.250.71.196
142.250.71.201
142.250.71.205
142.250.71.175
142.250.71.183
142.250.71.203
142.250.71.209
142.250.71.199
142.250.71.195
142.250.71.206
142.250.71.192
142.250.71.191
142.250.71.223
142.250.71.225
142.250.71.210
142.250.71.230
142.250.71.229
142.250.71.232
142.250.71.226
142.250.71.216
142.250.71.224
142.250.71.217
142.250.71.238
142.250.71.237
142.250.71.227
142.250.71.231
142.250.71.215
142.250.71.247
142.250.71.222
142.250.71.228
142.250.71.239
142.250.71.241
142.250.71.245
142.250.71.233
142.250.71.242
142.250.71.248
142.250.71.234
142.250.71.254
142.250.71.255
142.250.71.249
142.250.74.166
142.250.77.40
142.250.79.75
142.250.79.97
142.250.79.98
142.250.79.82
142.250.79.111
142.250.79.114
142.250.79.121
142.250.79.134
142.250.79.153
142.250.79.132
142.250.100.90
142.250.101.90
142.250.107.90
142.250.110.90
142.250.110.154
142.250.110.157
142.250.112.90
142.250.123.90
142.250.126.82
142.250.136.148
142.250.136.149
142.250.141.88
142.250.141.90
142.250.142.90
142.250.145.90
142.250.152.82
142.250.152.88
142.250.152.90
142.250.152.96
142.250.152.98
142.250.152.110
142.250.152.112
142.250.152.114
142.250.152.117
142.250.152.123
142.250.152.137
142.250.152.144
142.250.152.143
142.250.152.145
142.250.152.148
142.250.152.149
142.250.152.152
142.250.152.142
142.250.152.165
142.250.152.132
142.250.152.176
142.250.152.181
142.250.152.196
142.250.152.198
142.250.152.197
142.250.152.199
142.250.152.201
142.250.152.195
142.250.152.202
142.250.153.90
142.250.159.90
142.250.180.38
142.250.186.210
142.250.186.215
142.250.186.216
142.250.186.223
142.250.192.100
142.250.192.132
142.250.200.6
142.250.203.137
142.250.203.141
142.250.203.143
142.250.203.153
142.250.203.151
142.250.203.159
142.250.203.192
142.250.203.203
142.250.203.210
142.250.203.215
142.250.203.216
142.250.203.217
142.250.204.62
142.250.206.100
142.250.206.102
142.250.206.105
142.250.206.117
142.250.206.109
142.250.206.113
142.250.206.119
142.250.206.132
142.250.206.137
142.250.206.127
142.250.206.143
142.250.206.146
142.250.206.152
142.250.206.171
142.250.206.166
142.250.206.181
142.250.206.178
142.250.206.177
142.250.206.185
142.250.206.183
142.250.207.105
142.250.207.127

**Comment by Ponderfly** [comment]
216.239.32.40

**Comment by xinguo1236** [comment]
均显示的是超时，
142.250.206.127: 超时
142.250.206.146: 超时
142.250.206.152: 超时
142.250.206.166: 超时
142.250.206.171: 超时
142.250.206.181: 超时
142.250.206.178: 超时
142.250.123.90: 超时
142.250.206.185: 超时
142.250.206.183: 超时
142.250.207.105: 超时
142.250.207.127: 超时
216.239.32.40: 超时
未找到可用IP,可删除 ip.txt 文件直接进入扫描模式

再次麻烦您了，谢谢，请问还有其他方法吗



***@***.***
 
发件人： Ponderfly
发送时间： 2024-04-27 16:45
收件人： Ponderfly/GoogleTranslateIpCheck
抄送： xinguo1236; Author
主题： Re: [Ponderfly/GoogleTranslateIpCheck] 你好，hosts文件已添加64.233.188.144 translate.googleapis.com 64.233.188.144 translate.google.com 64.233.188.144 translate-pa.googleapis.com，但是还是无法进行英文网页的翻译，谷歌翻译的网页也无法进入，该如何解决呢，谢谢 (Issue #45)
216.239.32.40

**Comment by xinguo1236** [comment]
已经可以了，太感谢您了，祝您一切顺利
