### ISSUE TITLE
加个-v参数，让我查看当前程序的版本

### ISSUE THREAD

**Issue by omaidb** [Ponderfly/GoogleTranslateIpCheck#47]
感谢 @Ponderfly 大佬开发的这么好的程序，我好久没有更新程序了，不记得当时下载的是哪个版本了，不知道要不要更新。
希望能加个-v参数，让我查看当前程序的版本，决定要不要更新版本到最新。

**Comment by Ponderfly** [comment]
能用就无所谓,后续加上

**Comment by Ponderfly** [comment]
新版加上了
