### ISSUE TITLE
您好，谷歌翻译又不能正常使用了

### ISSUE THREAD

**Issue by xinguo1236** [Ponderfly/GoogleTranslateIpCheck#52]
您好，之前的216.239.32.40无法使用，我用GoogleTranslateIpCheck.exe扫描也没有得到可用IP，应该怎么解决呢，谢谢您

**Comment by Ponderfly** [comment]
Windows下试试这个版本进行扫描 : https://github.com/Ponderfly/GoogleTranslateIpCheck/releases/download/1.9/win-x64.TurboSyn.zip
