### ISSUE TITLE
当有稳定的ip的时候麻烦哪位大哥踢我一下

### ISSUE THREAD

**Issue by zhang-zhonggui** [Ponderfly/GoogleTranslateIpCheck#56]
现在Google的ip翻译太不稳定了，有可能上午设置的两三个小时失效了。现在我切换到微软去了，当有稳定的ip的时候麻烦哪位大哥踢我一下

**Comment by Ponderfly** [comment]
192.178.56.13
192.178.56.23
192.178.56.57
192.178.56.55
192.178.56.49
192.178.56.72
192.178.56.73
192.178.56.96
192.178.56.87
192.178.56.178
192.178.56.242
192.178.56.247
192.178.57.39
192.178.57.55
192.178.57.31

**Comment by BlackGu1tar** [comment]
全部挂了

**Comment by Ponderfly** [comment]
Warning: LINQPad has identified vulnerabilities in NuGet package Newtonsoft.Json. Click for details.
131070
142.250.72.78
142.250.74.8
142.250.77.46
142.250.178.68
142.250.178.72
142.250.178.69
142.250.178.67
142.250.178.71
142.250.178.70
142.250.178.74
142.250.178.73
142.250.178.81
142.250.178.78
142.250.178.79
142.250.178.85
142.250.178.87
142.250.178.89
142.250.178.88
142.250.178.102
142.250.178.96
142.250.178.94
142.250.178.99
142.250.178.98
142.250.178.95
142.250.178.97
142.250.178.101
142.250.178.100
142.250.178.106
142.250.178.107
142.250.178.105
142.250.178.109
142.250.178.114
142.250.178.110
142.250.178.111
142.250.178.104
142.250.178.113
142.250.178.117
142.250.178.119
142.250.178.120
142.250.178.121
142.250.178.126
142.250.178.127
142.250.179.68
142.250.183.70
142.250.191.38
142.250.193.238
142.250.194.35
142.250.194.131
142.250.203.89
142.251.1.97
142.251.2.81
142.251.15.101
142.251.16.82
142.251.16.148
142.251.41.4
142.251.134.131
142.251.140.4
142.251.163.93
142.251.163.120
142.251.163.136

**Comment by Ponderfly** [comment]
> 全部挂了

试试上面的

**Comment by Timleung1104** [comment]
> > 全部挂了
> 
> 试试上面的

刚刚试了  可以  不知能不能撑到明天

**Comment by dtGaoP** [comment]
2404:6800:4008:c13::5a  IPv6可用

**Comment by Ponderfly** [comment]
> @Ponderfly  大佬，知道谷歌浏览器里的字幕翻译功能吗？之前我以为是被链接延迟太高不行，但现在其他的都能用了，就是这个一直不能用

你用沉浸式翻译浏览器扩展就行了

**Comment by xxxqq55** [comment]
@Ponderfly 去看了下，好像并无法满足我的要求，他那个好像是视频网站双语字幕，但我并不需要。其实我是在看直播的时候开实时字幕

**Comment by xxxqq55** [comment]
@Ponderfly 我自己下了个抓包，好像是translation.googleapis.com。能不能加到软件里去，🎉

**Comment by Ponderfly** [comment]
> @Ponderfly 去看了下，好像并无法满足我的要求，他那个好像是视频网站双语字幕，但我并不需要。其实我是在看直播的时候开实时字幕

实时字幕是本地识别的，第一次用的时候会下载模型什么的，最好开个梯子看看

**Comment by xxxqq55** [comment]
@Ponderfly 我没说识别部分，我识别能正常用，就是打开翻译他就卡住了，我加了我说的那个host，可以恢复正常

**Comment by Ponderfly** [comment]
Windows下试试这个版本进行扫描 :  https://github.com/Ponderfly/GoogleTranslateIpCheck/releases/download/1.9/win-x64.TurboSyn.zip

**Comment by Ponderfly** [comment]
目前 v6 下面 这个比较稳定 : 2404:6800:4008:c13::5a

**Comment by xxxqq55** [comment]
@Ponderfly 我发现好像1.8的版本写的支持自定义添加Host域名，意思是可以自己添加translation.googleapis.com域名吗？我该怎么做呀，好像没看到说明

**Comment by Ponderfly** [comment]
> @Ponderfly 我发现好像1.8的版本写的支持自定义添加Host域名，意思是可以自己添加translation.googleapis.com域名吗？我该怎么做呀，好像没看到说明

这个你没必要手工去添加，添加跟翻译有关的域名

**Comment by xxxqq55** [comment]
@

> > @Ponderfly*  我发现好像1.8的版本写的支持自定义添加Host域名，意思是可以自己添加translation.googleapis.com域名吗？我该怎么做呀，好像没看到说明
> 
> 这个你没必要手工去添加，添加跟翻译有关的域名

我就是需要添加跟翻译有关的域名，😂，你现在软件自动添加的是translate.googleapis.com，translate.google.com，translate-pa.googleapis.com这3个域名，和我这个translation.googleapis.com不一样。

**Comment by Ponderfly** [comment]
> @
> 
> > > @Ponderfly*  我发现好像1.8的版本写的支持自定义添加Host域名，意思是可以自己添加translation.googleapis.com域名吗？我该怎么做呀，好像没看到说明
> > 
> > 这个你没必要手工去添加，添加跟翻译有关的域名
> 
> 我就是需要添加跟翻译有关的域名，😂，你现在软件自动添加的是translate.googleapis.com，translate.google.com，translate-pa.googleapis.com这3个域名，和我这个translation.googleapis.com不一样。

那就添加上
