### ISSUE TITLE
能不能做成后台一直跑？

### ISSUE THREAD

**Issue by nt47** [Ponderfly/GoogleTranslateIpCheck#57]
找到一个就覆盖host，无限循环🔄

**Comment by nt47** [comment]
> 找到一个就覆盖host，无限循环🔄

再出个动态版本吧～

**Comment by Timleung1104** [comment]
风险很大

**Comment by Ponderfly** [comment]
> 找到一个就覆盖host，无限循环🔄

试试这个版本, 使用 -t 启动 https://github.com/Ponderfly/GoogleTranslateIpCheck/releases/download/1.10/win-x64.TurboSyn.zip
