### ISSUE TITLE
今天的IP都不能用了

### ISSUE THREAD

**Issue by DourFeng** [Ponderfly/GoogleTranslateIpCheck#59]

**Comment by Ponderfly** [comment]
先用这个 2404:6800:4008:c13::5a

**Comment by xk-mt** [comment]
> 先用这个 2404:6800:4008:c13::5a

有没有ipv4的

**Comment by jackhbkgithub** [comment]
> > 先用这个 2404:6800:4008:c13::5a
> 
> 有没有ipv4的
173.194.192.100 这个今天暂时能用

**Comment by DourFeng** [comment]
v6可以

**Comment by Ponderfly** [comment]
Windows下试试这个版本进行扫描 :  https://github.com/Ponderfly/GoogleTranslateIpCheck/releases/download/1.9/win-x64.TurboSyn.zip

**Comment by xk-mt** [comment]
都不行

**Comment by Ponderfly** [comment]
> 都不行

用新版扫描
