### ISSUE TITLE
大佬你好，咨询一个github acrion的问题

### ISSUE THREAD

**Issue by stonegr** [Ponderfly/GoogleTranslateIpCheck#6]
大佬你好，我想问一下你的github action是怎么编译arm版本的可执行文件的呢？我也用python写了一些东西，能够编译amd64平台的，不知道arm版本的怎么操作，网上也没有找到，希望大佬指定指点，谢谢

无意扰乱issues秩序，不知道去哪里问了，谢谢

**Comment by Ponderfly** [comment]
我没用github action

**Comment by stonegr** [comment]
谢谢回复，不知道python要怎么去处理
