### ISSUE TITLE
今天是彻底用不了了，哪位知道发生了什么？

### ISSUE THREAD

**Issue by ahdung** [Ponderfly/GoogleTranslateIpCheck#65]
一个能用IP都扫不出，别的工具也一样，GoogleTranslate_IPFinder

**Comment by LGA1150** [comment]
用 [FOFA](https://fofa.info/result?qbase64=c2VydmVyPWd3cyAmJiBhc249IjM3OTYzIiAmJiBpY29uX2hhc2g9IjcwODU3ODIyOSI%3D) 可以找到在阿里云上的反向代理，不保证安全性，自己决定是否使用

**Comment by Ponderfly** [comment]
IPV6里面能用 ,4的可以先用https://github.com/BeyondDimension/SteamTools

**Comment by Ponderfly** [comment]
> 用 [FOFA](https://fofa.info/result?qbase64=c2VydmVyPWd3cyAmJiBhc249IjM3OTYzIiAmJiBpY29uX2hhc2g9IjcwODU3ODIyOSI%3D) 可以找到在阿里云上的反向代理，不保证安全性，自己决定是否使用

可用,安全翻译无所谓了

**Comment by ahdung** [comment]
@Ponderfly 这个SteamTools关翻译什么事，用到加速功能？

**Comment by ahdung** [comment]
@LGA1150 请教搜到的反代要怎样利用？把IP填进hosts就好？

**Comment by Ponderfly** [comment]
> @LGA1150 请教搜到的反代要怎样利用？把IP填进hosts就好？

120.79.81.149
47.115.32.167
120.25.234.79
47.103.15.240
随便选一个用

**Comment by Ponderfly** [comment]
> @Ponderfly 请教这个SteamTools关翻译什么事，用到加速功能？

IP不能用的时候再用这个

**Comment by ahdung** [comment]
@Ponderfly 这些IP是今天GoogleTranslateIpCheck扫到的，今天是能用了，我是说万一哪天用不了，那位老兄说的反代IP要怎么利用？另外你也没回答我是用到SteamTools的什么功能，如果只是加速，我都能上这里了，显然不需要加速器。

**Comment by Ponderfly** [comment]
> @Ponderfly 这些IP是今天GoogleTranslateIpCheck扫到的，今天是能用了，我是说万一哪天用不了，那位老兄说的反代IP要怎么利用？另外你也没回答我是用到SteamTools的什么功能，如果只是加速，我都能上这里了，显然不需要加速器。

当然是翻译加速功能

**Comment by Ponderfly** [comment]
GitHub 谷歌翻译 steam的不稳定都是一样处理方式，要一直稳定就用Watt Toolkit这类工具，缺点是需要一直运行，需要导入证书

**Comment by ahdung** [comment]
@Ponderfly 感谢解答，没想到这个SteamTools还有这种用处
